//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DataBaseAccessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Employees
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long Deparment_Id { get; set; }
    }
}
